# Generated by Django 5.1.1 on 2024-09-27 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeder_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('height', models.FloatField()),
                ('lifetime_from', models.IntegerField()),
                ('lifetime_to', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('photo_link', models.URLField(null=True)),
                ('breeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
